name: Android Unit Tests

on: [ push, pull_request, workflow_dispatch]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x eye_trainer/gradlew
    - name: Build with Gradle
      run: ./eye_trainer/gradlew build
    - name: Run unit tests
      run: ./eye_trainer/gradlew test
    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
